### ISSUE TITLE
can't find GCE image

### ISSUE THREAD

**Issue by vicenteg** [mapr/mapr-cloud-templates#1]
Hi, trying to install MapR from the 1.10 deployment manager template, and my deployment complains because it can't find an image called mapr-installer-t:

```
"The resource 'projects/my-project-id/global/images/maprinstaller-t"
```
How can I get ahold of this image?

**Comment by sfrolich** [comment]
Hi Vince. The GCE templates are not yet supported for automated deployments (Azure and AWS are). What you can do instead is create the VMs and resources needed in GCE then run the installer as you would for bare metal. Sorry for the inconvenience and let me know if you have any questions.

**Comment by vicenteg** [comment]
No problem - thanks!

**Comment by sfrolich** [comment]
@vicenteg ok if you need help choosing another means of getting MapR installed, let me know.
